### ISSUE TITLE
Migration to VueJs and more

### ISSUE THREAD

**Issue by Sebclem** [Sebclem/hassio-nextcloud-backup#192]
I'm currently migrating the addon to VueJs + Typescript, this will make the app more easy to maintain and i'm also planning to add some unit/e2e test.

With this migration I will also implement some long wanted features.
This issue is here to track my progress.

Features:
- [ ] Multiple cron #88 
- [ ] Chunked upload (This will prevent 413 errors #9)
- [ ] Home assistant status entity #1 
- [ ] Partial / Full backup support #63 
- [ ] Custom Webdav endpoint #108 #89 
- [ ] Rebuild status
- [ ] Tests

UI:
- [ ] Event viewer
- [ ] Status viewer
- [ ] Cloud config
- [ ] Backup config
- [ ] Backup viewer HA
- [ ] Backup viewer Cloud
